include:
  - project: 'github-mirror/ci-templates'
    file: '/.gitlab-ci-template.yml'

variables:
  COMPONENT_NAME: "board"
  DOCKERFILE_PATH: "Dockerfile"
  ENV_SUFFIX: "BOARD_PRODUCTION"
  ENV_FILE_DEST: "env/.production.env"
  ENV_FILE_BUILD_ARG: ".production.env"
  DEPLOYMENT_NAME: "board"
  CONTAINER_NAME: "board"
